apiVersion: kms.aws.upbound.io/v1beta1
kind: ReplicaExternalKey
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/replicaexternalkey
  labels:
    testing.upbound.io/example-name: replica
  name: replica
spec:
  forProvider:
    deletionWindowInDays: 7
    description: Multi-Region replica key
    keyMaterialBase64SecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    primaryKeyArn: ${aws_kms_external.primary.arn}
    region: us-west-1

---

apiVersion: kms.aws.upbound.io/v1beta1
kind: ExternalKey
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/replicaexternalkey
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    deletionWindowInDays: 30
    description: Multi-Region primary key
    enabled: true
    keyMaterialBase64SecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    multiRegion: true
    provider: ${aws.primary}
    region: us-west-1

---

