apiVersion: directconnect.aws.upbound.io/v1beta1
kind: HostedPrivateVirtualInterfaceAccepter
metadata:
  annotations:
    meta.upbound.io/example-id: directconnect/v1beta1/hostedprivatevirtualinterfaceaccepter
  labels:
    testing.upbound.io/example-name: accepter
  name: accepter
spec:
  forProvider:
    provider: ${aws.accepter}
    region: us-west-1
    tags:
      Side: Accepter
    virtualInterfaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: creator
    vpnGatewayId: ${aws_vpn_gateway.vpn_gw.id}

---

apiVersion: directconnect.aws.upbound.io/v1beta1
kind: HostedPrivateVirtualInterface
metadata:
  annotations:
    meta.upbound.io/example-id: directconnect/v1beta1/hostedprivatevirtualinterfaceaccepter
  labels:
    testing.upbound.io/example-name: creator
  name: creator
spec:
  forProvider:
    addressFamily: ipv4
    bgpAsn: 65352
    connectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: vif-foo
    ownerAccountId: ${data.aws_caller_identity.accepter.account_id}
    region: us-west-1
    vlan: 4094

---

