apiVersion: directconnect.aws.upbound.io/v1beta1
kind: HostedPrivateVirtualInterface
metadata:
  annotations:
    meta.upbound.io/example-id: directconnect/v1beta1/hostedprivatevirtualinterface
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    addressFamily: ipv4
    bgpAsn: 65352
    connectionId: dxcon-zzzzzzzz
    name: vif-foo
    region: us-west-1
    vlan: 4094

---

