apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/networkinterface
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    attachment:
    - deviceIndex: 1
      instanceSelector:
        matchLabels:
          testing.upbound.io/example-name: test
    privateIps:
    - 10.0.0.50
    region: us-west-1
    securityGroups:
    - ${aws_security_group.web.id}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: public_a

---

