apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/routetable
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    route:
    - cidrBlock: 10.0.1.0/24
      gatewayIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    - egressOnlyGatewayId: ${aws_egress_only_internet_gateway.example.id}
      ipv6CidrBlock: ::/0
    tags:
      Name: example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

